-- 插入100个NFC UID到bracelets表
-- 使用ON CONFLICT DO NOTHING确保幂等性
INSERT INTO bracelets (nfc_uid, status, created_at) VALUES 
('test-XLSOSZRH', 'available', NOW()),
('test-ZKPC68V9', 'available', NOW()),
('test-9Q218HA1', 'available', NOW()),
('test-Y1O23D1J', 'available', NOW()),
('test-543MGZGB', 'available', NOW()),
('test-SNQ09H00', 'available', NOW()),
('test-2YQV10UH', 'available', NOW()),
('test-U4FOB4AF', 'available', NOW()),
('test-VK6LC5E3', 'available', NOW()),
('test-FN9OWK5S', 'available', NOW()),
('test-BOGH6H1Z', 'available', NOW()),
('test-S68ONV8G', 'available', NOW()),
('test-IMAS8J6O', 'available', NOW()),
('test-MN47MC05', 'available', NOW()),
('test-1UXHCZZN', 'available', NOW()),
('test-7APK45OM', 'available', NOW()),
('test-STZTG46L', 'available', NOW()),
('test-9PCACO97', 'available', NOW()),
('test-OPRZQD0A', 'available', NOW()),
('test-3L8TDJBD', 'available', NOW()),
('test-CCOAM9LX', 'available', NOW()),
('test-G5R235WG', 'available', NOW()),
('test-STCLNRXV', 'available', NOW()),
('test-NV765UUT', 'available', NOW()),
('test-33OTO8F8', 'available', NOW()),
('test-SMMYO1O3', 'available', NOW()),
('test-5ODR73J5', 'available', NOW()),
('test-BN97LR6A', 'available', NOW()),
('test-Y1NNJ82O', 'available', NOW()),
('test-7H1S1JF8', 'available', NOW()),
('test-R0BHKYGJ', 'available', NOW()),
('test-EQO0VUBP', 'available', NOW()),
('test-2KS34AKC', 'available', NOW()),
('test-UFAMCNSS', 'available', NOW()),
('test-P1LDDAKW', 'available', NOW()),
('test-BWCII1I7', 'available', NOW()),
('test-9JKRJ156', 'available', NOW()),
('test-BU9PV46F', 'available', NOW()),
('test-H4II8YEN', 'available', NOW()),
('test-RMS2VW9C', 'available', NOW()),
('test-5F70XINJ', 'available', NOW()),
('test-BEUBVMCA', 'available', NOW()),
('test-EOBGQ0W6', 'available', NOW()),
('test-LOJZWHAS', 'available', NOW()),
('test-L4S1KNJ6', 'available', NOW()),
('test-J2TLQFPL', 'available', NOW()),
('test-YPLKJ5N9', 'available', NOW()),
('test-GMB9PL9C', 'available', NOW()),
('test-IHW016WL', 'available', NOW()),
('test-30DPZONP', 'available', NOW()),
('test-WJVYLE4I', 'available', NOW()),
('test-73T4576J', 'available', NOW()),
('test-SE0L7ROO', 'available', NOW()),
('test-6EF25MHE', 'available', NOW()),
('test-DBAUTL3Y', 'available', NOW()),
('test-KKHOJ7BI', 'available', NOW()),
('test-0PRAKLGU', 'available', NOW()),
('test-6K1ODV3N', 'available', NOW()),
('test-VWUPDHKN', 'available', NOW()),
('test-H0M7LP9N', 'available', NOW()),
('test-OEMP4Y4V', 'available', NOW()),
('test-J4806MCJ', 'available', NOW()),
('test-T1OA8WVE', 'available', NOW()),
('test-LZKFA2AD', 'available', NOW()),
('test-CZVNFWGG', 'available', NOW()),
('test-S10N53J5', 'available', NOW()),
('test-0RJ9RQ9I', 'available', NOW()),
('test-YX62GBPT', 'available', NOW()),
('test-AU8KVGM9', 'available', NOW()),
('test-MVDI2RNO', 'available', NOW()),
('test-5NB8IQZV', 'available', NOW()),
('test-RZVC0M5V', 'available', NOW()),
('test-713IJTCV', 'available', NOW()),
('test-9Y2RRA4D', 'available', NOW()),
('test-S2Y3O5CT', 'available', NOW()),
('test-KV39ARDO', 'available', NOW()),
('test-L2U3SK4B', 'available', NOW()),
('test-MKDWJ5YS', 'available', NOW()),
('test-XLJGI9IC', 'available', NOW()),
('test-KCRUBEY0', 'available', NOW()),
('test-L0C7RC7M', 'available', NOW()),
('test-XETM8801', 'available', NOW()),
('test-A4NDCLSJ', 'available', NOW()),
('test-2YN77L99', 'available', NOW()),
('test-X6R9E0BJ', 'available', NOW()),
('test-FEQDHI4Y', 'available', NOW()),
('test-BCQLZL9F', 'available', NOW()),
('test-9HQFJ5T3', 'available', NOW()),
('test-QXPO6BRW', 'available', NOW()),
('test-F8JM2UU4', 'available', NOW()),
('test-WC8AZ02G', 'available', NOW()),
('test-OETKH1CJ', 'available', NOW()),
('test-GUYS64US', 'available', NOW()),
('test-GL8EDSIF', 'available', NOW()),
('test-XGZY0DK2', 'available', NOW()),
('test-436DJQ40', 'available', NOW()),
('test-D48ETZOG', 'available', NOW()),
('test-0DA3D04G', 'available', NOW()),
('test-MI7TVM7V', 'available', NOW()),
('test-LKW2CD9H', 'available', NOW())
ON CONFLICT (nfc_uid) DO NOTHING;

-- 验证插入结果
SELECT COUNT(*) as total_uids FROM bracelets WHERE nfc_uid LIKE 'test-%';

-- 查看插入的UID（前10个）
SELECT nfc_uid, status, created_at FROM bracelets 
WHERE nfc_uid LIKE 'test-%' 
ORDER BY nfc_uid 
LIMIT 10;
